### ISSUE TITLE
Basit açık

### ISSUE THREAD

**Issue by This-null** [richardsistemler/richard-sekme-korumasi#1]
Google üzeri girdikten sonra mobil veya uygulamadan giriş yapınca rolleriniz geri verilir.

Kısaca platformlar arası geçişlerde sunucuya vurmak isteyen adam istediğini yapar.

**Comment by richardsistemler** [comment]
bro sence ben bunu bilmiyorumuyum veya daha doğrusu umrum da mı?

**Comment by This-null** [comment]
k
